using System;
using Il2CppInterop.Common.Attributes;
using Il2CppInterop.Runtime;
using Il2CppInterop.Runtime.InteropTypes.Arrays;
using Il2CppInterop.Runtime.Runtime;
using Il2CppSystem.Collections;
using Il2CppSystem.ComponentModel;

namespace Il2CppSystem.Data
{
	// Token: 0x02000023 RID: 35
	public sealed class ConstraintCollection : InternalDataCollectionBase
	{
		// Token: 0x060004CD RID: 1229 RVA: 0x0001DFD4 File Offset: 0x0001C1D4
		// Note: this type is marked as 'beforefieldinit'.
		static ConstraintCollection()
		{
			Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr = IL2CPP.GetIl2CppClass("System.Data.dll", "System.Data", "ConstraintCollection");
			IL2CPP.il2cpp_runtime_class_init(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr);
			ConstraintCollection.NativeFieldInfoPtr__table = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, "_table");
			ConstraintCollection.NativeFieldInfoPtr__list = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, "_list");
			ConstraintCollection.NativeFieldInfoPtr__defaultNameIndex = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, "_defaultNameIndex");
			ConstraintCollection.NativeFieldInfoPtr__onCollectionChanged = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, "_onCollectionChanged");
			ConstraintCollection.NativeFieldInfoPtr__delayLoadingConstraints = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, "_delayLoadingConstraints");
			ConstraintCollection.NativeFieldInfoPtr__fLoadForeignKeyConstraintsOnly = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, "_fLoadForeignKeyConstraintsOnly");
			ConstraintCollection.NativeMethodInfoPtr__ctor_Internal_Void_DataTable_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664135);
			ConstraintCollection.NativeMethodInfoPtr_get_List_Protected_Virtual_get_ArrayList_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664136);
			ConstraintCollection.NativeMethodInfoPtr_get_Item_Public_get_Constraint_Int32_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664137);
			ConstraintCollection.NativeMethodInfoPtr_get_Table_Internal_get_DataTable_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664138);
			ConstraintCollection.NativeMethodInfoPtr_get_Item_Public_get_Constraint_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664139);
			ConstraintCollection.NativeMethodInfoPtr_Add_Public_Void_Constraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664140);
			ConstraintCollection.NativeMethodInfoPtr_Add_Internal_Void_Constraint_Boolean_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664141);
			ConstraintCollection.NativeMethodInfoPtr_Add_Public_Constraint_String_Il2CppReferenceArray_1_DataColumn_Boolean_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664142);
			ConstraintCollection.NativeMethodInfoPtr_AddUniqueConstraint_Private_Void_UniqueConstraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664143);
			ConstraintCollection.NativeMethodInfoPtr_AddForeignKeyConstraint_Private_Void_ForeignKeyConstraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664144);
			ConstraintCollection.NativeMethodInfoPtr_AutoGenerated_Private_Boolean_Constraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664145);
			ConstraintCollection.NativeMethodInfoPtr_ArrayAdd_Private_Void_Constraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664146);
			ConstraintCollection.NativeMethodInfoPtr_ArrayRemove_Private_Void_Constraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664147);
			ConstraintCollection.NativeMethodInfoPtr_AssignName_Internal_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664148);
			ConstraintCollection.NativeMethodInfoPtr_BaseAdd_Private_Void_Constraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664149);
			ConstraintCollection.NativeMethodInfoPtr_BaseGroupSwitch_Private_Void_Il2CppReferenceArray_1_Constraint_Int32_Il2CppReferenceArray_1_Constraint_Int32_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664150);
			ConstraintCollection.NativeMethodInfoPtr_BaseRemove_Private_Void_Constraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664151);
			ConstraintCollection.NativeMethodInfoPtr_CanRemove_Internal_Boolean_Constraint_Boolean_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664152);
			ConstraintCollection.NativeMethodInfoPtr_Clear_Public_Void_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664153);
			ConstraintCollection.NativeMethodInfoPtr_Contains_Public_Boolean_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664154);
			ConstraintCollection.NativeMethodInfoPtr_Contains_Internal_Boolean_String_Boolean_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664155);
			ConstraintCollection.NativeMethodInfoPtr_FindConstraint_Internal_Constraint_Constraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664156);
			ConstraintCollection.NativeMethodInfoPtr_FindKeyConstraint_Internal_UniqueConstraint_Il2CppReferenceArray_1_DataColumn_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664157);
			ConstraintCollection.NativeMethodInfoPtr_FindKeyConstraint_Internal_UniqueConstraint_DataColumn_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664158);
			ConstraintCollection.NativeMethodInfoPtr_FindForeignKeyConstraint_Internal_ForeignKeyConstraint_Il2CppReferenceArray_1_DataColumn_Il2CppReferenceArray_1_DataColumn_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664159);
			ConstraintCollection.NativeMethodInfoPtr_CompareArrays_Private_Static_Boolean_Il2CppReferenceArray_1_DataColumn_Il2CppReferenceArray_1_DataColumn_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664160);
			ConstraintCollection.NativeMethodInfoPtr_InternalIndexOf_Internal_Int32_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664161);
			ConstraintCollection.NativeMethodInfoPtr_MakeName_Private_String_Int32_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664162);
			ConstraintCollection.NativeMethodInfoPtr_OnCollectionChanged_Private_Void_CollectionChangeEventArgs_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664163);
			ConstraintCollection.NativeMethodInfoPtr_RegisterName_Internal_Void_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664164);
			ConstraintCollection.NativeMethodInfoPtr_Remove_Public_Void_Constraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664165);
			ConstraintCollection.NativeMethodInfoPtr_UnregisterName_Internal_Void_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr, 100664166);
		}

		// Token: 0x060004CE RID: 1230 RVA: 0x0001E2FC File Offset: 0x0001C4FC
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 898216, RefRangeEnd = 898217, XrefRangeStart = 898206, XrefRangeEnd = 898216, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe ConstraintCollection(DataTable table)
			: this(IL2CPP.il2cpp_object_new(Il2CppClassPointerStore<ConstraintCollection>.NativeClassPtr))
		{
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(table);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr__ctor_Internal_Void_DataTable_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x17000131 RID: 305
		// (get) Token: 0x060004CF RID: 1231 RVA: 0x0001E348 File Offset: 0x0001C548
		public unsafe override ArrayList List
		{
			[CallerCount(15)]
			[CachedScanResults(RefRangeStart = 3282, RefRangeEnd = 3297, XrefRangeStart = 3282, XrefRangeEnd = 3297, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
			get
			{
				IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IntPtr* ptr = null;
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_get_List_Protected_Virtual_get_ArrayList_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				IntPtr intPtr3 = intPtr;
				return (intPtr3 != 0) ? Il2CppObjectPool.Get<ArrayList>(intPtr3) : null;
			}
		}

		// Token: 0x17000132 RID: 306
		public unsafe Constraint this[int index]
		{
			[CallerCount(22)]
			[CachedScanResults(RefRangeStart = 898219, RefRangeEnd = 898241, XrefRangeStart = 898217, XrefRangeEnd = 898219, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
			get
			{
				IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				checked
				{
					IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
					*ptr = ref index;
					IntPtr intPtr2;
					IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_get_Item_Public_get_Constraint_Int32_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
					Il2CppException.RaiseExceptionIfNecessary(intPtr2);
					IntPtr intPtr3 = intPtr;
					return (intPtr3 != 0) ? Il2CppObjectPool.Get<Constraint>(intPtr3) : null;
				}
			}
		}

		// Token: 0x17000133 RID: 307
		// (get) Token: 0x060004D1 RID: 1233 RVA: 0x0001E3D4 File Offset: 0x0001C5D4
		public unsafe DataTable Table
		{
			[CallerCount(10)]
			[CachedScanResults(RefRangeStart = 123248, RefRangeEnd = 123258, XrefRangeStart = 123248, XrefRangeEnd = 123258, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
			get
			{
				IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IntPtr* ptr = null;
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_get_Table_Internal_get_DataTable_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				IntPtr intPtr3 = intPtr;
				return (intPtr3 != 0) ? Il2CppObjectPool.Get<DataTable>(intPtr3) : null;
			}
		}

		// Token: 0x17000134 RID: 308
		public unsafe Constraint this[string name]
		{
			[CallerCount(1)]
			[CachedScanResults(RefRangeStart = 898243, RefRangeEnd = 898244, XrefRangeStart = 898241, XrefRangeEnd = 898243, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
			get
			{
				IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				checked
				{
					IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
					*ptr = IL2CPP.ManagedStringToIl2Cpp(name);
					IntPtr intPtr2;
					IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_get_Item_Public_get_Constraint_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
					Il2CppException.RaiseExceptionIfNecessary(intPtr2);
					IntPtr intPtr3 = intPtr;
					return (intPtr3 != 0) ? Il2CppObjectPool.Get<Constraint>(intPtr3) : null;
				}
			}
		}

		// Token: 0x060004D3 RID: 1235 RVA: 0x0001E464 File Offset: 0x0001C664
		[CallerCount(9)]
		[CachedScanResults(RefRangeStart = 898245, RefRangeEnd = 898254, XrefRangeStart = 898244, XrefRangeEnd = 898245, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void Add(Constraint constraint)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_Add_Public_Void_Constraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004D4 RID: 1236 RVA: 0x0001E4A8 File Offset: 0x0001C6A8
		[CallerCount(5)]
		[CachedScanResults(RefRangeStart = 898289, RefRangeEnd = 898294, XrefRangeStart = 898254, XrefRangeEnd = 898289, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void Add(Constraint constraint, bool addUniqueWhenAddingForeign)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref addUniqueWhenAddingForeign;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_Add_Internal_Void_Constraint_Boolean_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x060004D5 RID: 1237 RVA: 0x0001E4F8 File Offset: 0x0001C6F8
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 898300, RefRangeEnd = 898301, XrefRangeStart = 898294, XrefRangeEnd = 898300, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe Constraint Add(string name, Il2CppReferenceArray<DataColumn> columns, bool primaryKey)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.ManagedStringToIl2Cpp(name);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(columns);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref primaryKey;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_Add_Public_Constraint_String_Il2CppReferenceArray_1_DataColumn_Boolean_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<Constraint>(intPtr3) : null;
		}

		// Token: 0x060004D6 RID: 1238 RVA: 0x0001E568 File Offset: 0x0001C768
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 898301, XrefRangeEnd = 898304, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void AddUniqueConstraint(UniqueConstraint constraint)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_AddUniqueConstraint_Private_Void_UniqueConstraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004D7 RID: 1239 RVA: 0x0001E5AC File Offset: 0x0001C7AC
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 898304, XrefRangeEnd = 898308, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void AddForeignKeyConstraint(ForeignKeyConstraint constraint)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_AddForeignKeyConstraint_Private_Void_ForeignKeyConstraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004D8 RID: 1240 RVA: 0x0001E5F0 File Offset: 0x0001C7F0
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 898308, XrefRangeEnd = 898317, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe bool AutoGenerated(Constraint constraint)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_AutoGenerated_Private_Boolean_Constraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x060004D9 RID: 1241 RVA: 0x0001E640 File Offset: 0x0001C840
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 898317, XrefRangeEnd = 898318, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void ArrayAdd(Constraint constraint)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_ArrayAdd_Private_Void_Constraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004DA RID: 1242 RVA: 0x0001E684 File Offset: 0x0001C884
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 898318, XrefRangeEnd = 898319, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void ArrayRemove(Constraint constraint)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_ArrayRemove_Private_Void_Constraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004DB RID: 1243 RVA: 0x0001E6C8 File Offset: 0x0001C8C8
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 898319, XrefRangeEnd = 898320, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe string AssignName()
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr = null;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_AssignName_Internal_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			return IL2CPP.Il2CppStringToManaged(intPtr);
		}

		// Token: 0x060004DC RID: 1244 RVA: 0x0001E700 File Offset: 0x0001C900
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 898328, RefRangeEnd = 898330, XrefRangeStart = 898320, XrefRangeEnd = 898328, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void BaseAdd(Constraint constraint)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_BaseAdd_Private_Void_Constraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004DD RID: 1245 RVA: 0x0001E744 File Offset: 0x0001C944
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 898330, XrefRangeEnd = 898334, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void BaseGroupSwitch(Il2CppReferenceArray<Constraint> oldArray, int oldLength, Il2CppReferenceArray<Constraint> newArray, int newLength)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)4) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(oldArray);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref oldLength;
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(newArray);
			ptr[checked(unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref newLength;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_BaseGroupSwitch_Private_Void_Il2CppReferenceArray_1_Constraint_Int32_Il2CppReferenceArray_1_Constraint_Int32_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x060004DE RID: 1246 RVA: 0x0001E7B4 File Offset: 0x0001C9B4
		[CallerCount(3)]
		[CachedScanResults(RefRangeStart = 898344, RefRangeEnd = 898347, XrefRangeStart = 898334, XrefRangeEnd = 898344, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void BaseRemove(Constraint constraint)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_BaseRemove_Private_Void_Constraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004DF RID: 1247 RVA: 0x0001E7F8 File Offset: 0x0001C9F8
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 898348, RefRangeEnd = 898350, XrefRangeStart = 898347, XrefRangeEnd = 898348, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe bool CanRemove(Constraint constraint, bool fThrowException)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref fThrowException;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_CanRemove_Internal_Boolean_Constraint_Boolean_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			return *IL2CPP.il2cpp_object_unbox(intPtr);
		}

		// Token: 0x060004E0 RID: 1248 RVA: 0x0001E854 File Offset: 0x0001CA54
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 898369, RefRangeEnd = 898371, XrefRangeStart = 898350, XrefRangeEnd = 898369, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void Clear()
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr = null;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_Clear_Public_Void_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x060004E1 RID: 1249 RVA: 0x0001E888 File Offset: 0x0001CA88
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 898372, RefRangeEnd = 898373, XrefRangeStart = 898371, XrefRangeEnd = 898372, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe bool Contains(string name)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.ManagedStringToIl2Cpp(name);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_Contains_Public_Boolean_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x060004E2 RID: 1250 RVA: 0x0001E8D8 File Offset: 0x0001CAD8
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 898377, RefRangeEnd = 898378, XrefRangeStart = 898373, XrefRangeEnd = 898377, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe bool Contains(string name, bool caseSensitive)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.ManagedStringToIl2Cpp(name);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref caseSensitive;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_Contains_Internal_Boolean_String_Boolean_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			return *IL2CPP.il2cpp_object_unbox(intPtr);
		}

		// Token: 0x060004E3 RID: 1251 RVA: 0x0001E934 File Offset: 0x0001CB34
		[CallerCount(6)]
		[CachedScanResults(RefRangeStart = 898380, RefRangeEnd = 898386, XrefRangeStart = 898378, XrefRangeEnd = 898380, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe Constraint FindConstraint(Constraint constraint)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_FindConstraint_Internal_Constraint_Constraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				IntPtr intPtr3 = intPtr;
				return (intPtr3 != 0) ? Il2CppObjectPool.Get<Constraint>(intPtr3) : null;
			}
		}

		// Token: 0x060004E4 RID: 1252 RVA: 0x0001E984 File Offset: 0x0001CB84
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 898390, RefRangeEnd = 898392, XrefRangeStart = 898386, XrefRangeEnd = 898390, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe UniqueConstraint FindKeyConstraint(Il2CppReferenceArray<DataColumn> columns)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(columns);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_FindKeyConstraint_Internal_UniqueConstraint_Il2CppReferenceArray_1_DataColumn_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				IntPtr intPtr3 = intPtr;
				return (intPtr3 != 0) ? Il2CppObjectPool.Get<UniqueConstraint>(intPtr3) : null;
			}
		}

		// Token: 0x060004E5 RID: 1253 RVA: 0x0001E9D4 File Offset: 0x0001CBD4
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 898395, RefRangeEnd = 898397, XrefRangeStart = 898392, XrefRangeEnd = 898395, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe UniqueConstraint FindKeyConstraint(DataColumn column)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(column);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_FindKeyConstraint_Internal_UniqueConstraint_DataColumn_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				IntPtr intPtr3 = intPtr;
				return (intPtr3 != 0) ? Il2CppObjectPool.Get<UniqueConstraint>(intPtr3) : null;
			}
		}

		// Token: 0x060004E6 RID: 1254 RVA: 0x0001EA24 File Offset: 0x0001CC24
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 898404, RefRangeEnd = 898406, XrefRangeStart = 898397, XrefRangeEnd = 898404, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe ForeignKeyConstraint FindForeignKeyConstraint(Il2CppReferenceArray<DataColumn> parentColumns, Il2CppReferenceArray<DataColumn> childColumns)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(parentColumns);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(childColumns);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_FindForeignKeyConstraint_Internal_ForeignKeyConstraint_Il2CppReferenceArray_1_DataColumn_Il2CppReferenceArray_1_DataColumn_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<ForeignKeyConstraint>(intPtr3) : null;
		}

		// Token: 0x060004E7 RID: 1255 RVA: 0x0001EA88 File Offset: 0x0001CC88
		[CallerCount(3)]
		[CachedScanResults(RefRangeStart = 898408, RefRangeEnd = 898411, XrefRangeStart = 898406, XrefRangeEnd = 898408, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static bool CompareArrays(Il2CppReferenceArray<DataColumn> a1, Il2CppReferenceArray<DataColumn> a2)
		{
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(a1);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(a2);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_CompareArrays_Private_Static_Boolean_Il2CppReferenceArray_1_DataColumn_Il2CppReferenceArray_1_DataColumn_0, 0, (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			return *IL2CPP.il2cpp_object_unbox(intPtr);
		}

		// Token: 0x060004E8 RID: 1256 RVA: 0x0001EADC File Offset: 0x0001CCDC
		[CallerCount(5)]
		[CachedScanResults(RefRangeStart = 898414, RefRangeEnd = 898419, XrefRangeStart = 898411, XrefRangeEnd = 898414, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe int InternalIndexOf(string constraintName)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.ManagedStringToIl2Cpp(constraintName);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_InternalIndexOf_Internal_Int32_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x060004E9 RID: 1257 RVA: 0x0001EB2C File Offset: 0x0001CD2C
		[CallerCount(6)]
		[CachedScanResults(RefRangeStart = 898428, RefRangeEnd = 898434, XrefRangeStart = 898419, XrefRangeEnd = 898428, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe string MakeName(int index)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = ref index;
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_MakeName_Private_String_Int32_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return IL2CPP.Il2CppStringToManaged(intPtr);
			}
		}

		// Token: 0x060004EA RID: 1258 RVA: 0x0001EB70 File Offset: 0x0001CD70
		[CallerCount(0)]
		public unsafe void OnCollectionChanged(CollectionChangeEventArgs ccevent)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(ccevent);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_OnCollectionChanged_Private_Void_CollectionChangeEventArgs_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004EB RID: 1259 RVA: 0x0001EBB4 File Offset: 0x0001CDB4
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 898439, RefRangeEnd = 898441, XrefRangeStart = 898434, XrefRangeEnd = 898439, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void RegisterName(string name)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.ManagedStringToIl2Cpp(name);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_RegisterName_Internal_Void_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004EC RID: 1260 RVA: 0x0001EBF8 File Offset: 0x0001CDF8
		[CallerCount(3)]
		[CachedScanResults(RefRangeStart = 898450, RefRangeEnd = 898453, XrefRangeStart = 898441, XrefRangeEnd = 898450, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void Remove(Constraint constraint)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(constraint);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_Remove_Public_Void_Constraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004ED RID: 1261 RVA: 0x0001EC3C File Offset: 0x0001CE3C
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 898457, RefRangeEnd = 898458, XrefRangeStart = 898453, XrefRangeEnd = 898457, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void UnregisterName(string name)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.ManagedStringToIl2Cpp(name);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(ConstraintCollection.NativeMethodInfoPtr_UnregisterName_Internal_Void_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x060004EE RID: 1262 RVA: 0x0000351A File Offset: 0x0000171A
		public ConstraintCollection(IntPtr pointer)
			: base(pointer)
		{
		}

		// Token: 0x1700012B RID: 299
		// (get) Token: 0x060004EF RID: 1263 RVA: 0x0001EC80 File Offset: 0x0001CE80
		// (set) Token: 0x060004F0 RID: 1264 RVA: 0x00003523 File Offset: 0x00001723
		public unsafe DataTable _table
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__table);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<DataTable>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__table), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x1700012C RID: 300
		// (get) Token: 0x060004F1 RID: 1265 RVA: 0x0001ECB0 File Offset: 0x0001CEB0
		// (set) Token: 0x060004F2 RID: 1266 RVA: 0x00003542 File Offset: 0x00001742
		public unsafe ArrayList _list
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__list);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<ArrayList>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__list), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x1700012D RID: 301
		// (get) Token: 0x060004F3 RID: 1267 RVA: 0x0001ECE0 File Offset: 0x0001CEE0
		// (set) Token: 0x060004F4 RID: 1268 RVA: 0x00003561 File Offset: 0x00001761
		public unsafe int _defaultNameIndex
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__defaultNameIndex);
				return *intPtr;
			}
			set
			{
				*(IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__defaultNameIndex)) = value;
			}
		}

		// Token: 0x1700012E RID: 302
		// (get) Token: 0x060004F5 RID: 1269 RVA: 0x0001ED08 File Offset: 0x0001CF08
		// (set) Token: 0x060004F6 RID: 1270 RVA: 0x0000357C File Offset: 0x0000177C
		public unsafe CollectionChangeEventHandler _onCollectionChanged
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__onCollectionChanged);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<CollectionChangeEventHandler>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__onCollectionChanged), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x1700012F RID: 303
		// (get) Token: 0x060004F7 RID: 1271 RVA: 0x0001ED38 File Offset: 0x0001CF38
		// (set) Token: 0x060004F8 RID: 1272 RVA: 0x0000359B File Offset: 0x0000179B
		public unsafe Il2CppReferenceArray<Constraint> _delayLoadingConstraints
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__delayLoadingConstraints);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<Il2CppReferenceArray<Constraint>>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__delayLoadingConstraints), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x17000130 RID: 304
		// (get) Token: 0x060004F9 RID: 1273 RVA: 0x0001ED68 File Offset: 0x0001CF68
		// (set) Token: 0x060004FA RID: 1274 RVA: 0x000035BA File Offset: 0x000017BA
		public unsafe bool _fLoadForeignKeyConstraintsOnly
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__fLoadForeignKeyConstraintsOnly);
				return *intPtr;
			}
			set
			{
				*(IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(ConstraintCollection.NativeFieldInfoPtr__fLoadForeignKeyConstraintsOnly)) = value;
			}
		}

		// Token: 0x04000416 RID: 1046
		private static readonly IntPtr NativeFieldInfoPtr__table;

		// Token: 0x04000417 RID: 1047
		private static readonly IntPtr NativeFieldInfoPtr__list;

		// Token: 0x04000418 RID: 1048
		private static readonly IntPtr NativeFieldInfoPtr__defaultNameIndex;

		// Token: 0x04000419 RID: 1049
		private static readonly IntPtr NativeFieldInfoPtr__onCollectionChanged;

		// Token: 0x0400041A RID: 1050
		private static readonly IntPtr NativeFieldInfoPtr__delayLoadingConstraints;

		// Token: 0x0400041B RID: 1051
		private static readonly IntPtr NativeFieldInfoPtr__fLoadForeignKeyConstraintsOnly;

		// Token: 0x0400041C RID: 1052
		private static readonly IntPtr NativeMethodInfoPtr__ctor_Internal_Void_DataTable_0;

		// Token: 0x0400041D RID: 1053
		private static readonly IntPtr NativeMethodInfoPtr_get_List_Protected_Virtual_get_ArrayList_0;

		// Token: 0x0400041E RID: 1054
		private static readonly IntPtr NativeMethodInfoPtr_get_Item_Public_get_Constraint_Int32_0;

		// Token: 0x0400041F RID: 1055
		private static readonly IntPtr NativeMethodInfoPtr_get_Table_Internal_get_DataTable_0;

		// Token: 0x04000420 RID: 1056
		private static readonly IntPtr NativeMethodInfoPtr_get_Item_Public_get_Constraint_String_0;

		// Token: 0x04000421 RID: 1057
		private static readonly IntPtr NativeMethodInfoPtr_Add_Public_Void_Constraint_0;

		// Token: 0x04000422 RID: 1058
		private static readonly IntPtr NativeMethodInfoPtr_Add_Internal_Void_Constraint_Boolean_0;

		// Token: 0x04000423 RID: 1059
		private static readonly IntPtr NativeMethodInfoPtr_Add_Public_Constraint_String_Il2CppReferenceArray_1_DataColumn_Boolean_0;

		// Token: 0x04000424 RID: 1060
		private static readonly IntPtr NativeMethodInfoPtr_AddUniqueConstraint_Private_Void_UniqueConstraint_0;

		// Token: 0x04000425 RID: 1061
		private static readonly IntPtr NativeMethodInfoPtr_AddForeignKeyConstraint_Private_Void_ForeignKeyConstraint_0;

		// Token: 0x04000426 RID: 1062
		private static readonly IntPtr NativeMethodInfoPtr_AutoGenerated_Private_Boolean_Constraint_0;

		// Token: 0x04000427 RID: 1063
		private static readonly IntPtr NativeMethodInfoPtr_ArrayAdd_Private_Void_Constraint_0;

		// Token: 0x04000428 RID: 1064
		private static readonly IntPtr NativeMethodInfoPtr_ArrayRemove_Private_Void_Constraint_0;

		// Token: 0x04000429 RID: 1065
		private static readonly IntPtr NativeMethodInfoPtr_AssignName_Internal_String_0;

		// Token: 0x0400042A RID: 1066
		private static readonly IntPtr NativeMethodInfoPtr_BaseAdd_Private_Void_Constraint_0;

		// Token: 0x0400042B RID: 1067
		private static readonly IntPtr NativeMethodInfoPtr_BaseGroupSwitch_Private_Void_Il2CppReferenceArray_1_Constraint_Int32_Il2CppReferenceArray_1_Constraint_Int32_0;

		// Token: 0x0400042C RID: 1068
		private static readonly IntPtr NativeMethodInfoPtr_BaseRemove_Private_Void_Constraint_0;

		// Token: 0x0400042D RID: 1069
		private static readonly IntPtr NativeMethodInfoPtr_CanRemove_Internal_Boolean_Constraint_Boolean_0;

		// Token: 0x0400042E RID: 1070
		private static readonly IntPtr NativeMethodInfoPtr_Clear_Public_Void_0;

		// Token: 0x0400042F RID: 1071
		private static readonly IntPtr NativeMethodInfoPtr_Contains_Public_Boolean_String_0;

		// Token: 0x04000430 RID: 1072
		private static readonly IntPtr NativeMethodInfoPtr_Contains_Internal_Boolean_String_Boolean_0;

		// Token: 0x04000431 RID: 1073
		private static readonly IntPtr NativeMethodInfoPtr_FindConstraint_Internal_Constraint_Constraint_0;

		// Token: 0x04000432 RID: 1074
		private static readonly IntPtr NativeMethodInfoPtr_FindKeyConstraint_Internal_UniqueConstraint_Il2CppReferenceArray_1_DataColumn_0;

		// Token: 0x04000433 RID: 1075
		private static readonly IntPtr NativeMethodInfoPtr_FindKeyConstraint_Internal_UniqueConstraint_DataColumn_0;

		// Token: 0x04000434 RID: 1076
		private static readonly IntPtr NativeMethodInfoPtr_FindForeignKeyConstraint_Internal_ForeignKeyConstraint_Il2CppReferenceArray_1_DataColumn_Il2CppReferenceArray_1_DataColumn_0;

		// Token: 0x04000435 RID: 1077
		private static readonly IntPtr NativeMethodInfoPtr_CompareArrays_Private_Static_Boolean_Il2CppReferenceArray_1_DataColumn_Il2CppReferenceArray_1_DataColumn_0;

		// Token: 0x04000436 RID: 1078
		private static readonly IntPtr NativeMethodInfoPtr_InternalIndexOf_Internal_Int32_String_0;

		// Token: 0x04000437 RID: 1079
		private static readonly IntPtr NativeMethodInfoPtr_MakeName_Private_String_Int32_0;

		// Token: 0x04000438 RID: 1080
		private static readonly IntPtr NativeMethodInfoPtr_OnCollectionChanged_Private_Void_CollectionChangeEventArgs_0;

		// Token: 0x04000439 RID: 1081
		private static readonly IntPtr NativeMethodInfoPtr_RegisterName_Internal_Void_String_0;

		// Token: 0x0400043A RID: 1082
		private static readonly IntPtr NativeMethodInfoPtr_Remove_Public_Void_Constraint_0;

		// Token: 0x0400043B RID: 1083
		private static readonly IntPtr NativeMethodInfoPtr_UnregisterName_Internal_Void_String_0;
	}
}
