using System;
using Il2CppInterop.Common.Attributes;
using Il2CppInterop.Runtime;
using Il2CppInterop.Runtime.InteropTypes.Arrays;
using Il2CppInterop.Runtime.Runtime;
using Il2CppSystem.Collections;
using Il2CppSystem.ComponentModel;
using Il2CppSystem.Xml;

namespace Il2CppSystem.Data
{
	// Token: 0x02000085 RID: 133
	public sealed class XmlTreeGen : Object
	{
		// Token: 0x06000C8C RID: 3212 RVA: 0x0003F498 File Offset: 0x0003D698
		// Note: this type is marked as 'beforefieldinit'.
		static XmlTreeGen()
		{
			Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr = IL2CPP.GetIl2CppClass("System.Data.dll", "System.Data", "XmlTreeGen");
			IL2CPP.il2cpp_runtime_class_init(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr);
			XmlTreeGen.NativeFieldInfoPtr__constraintNames = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_constraintNames");
			XmlTreeGen.NativeFieldInfoPtr__namespaces = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_namespaces");
			XmlTreeGen.NativeFieldInfoPtr__autogenerated = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_autogenerated");
			XmlTreeGen.NativeFieldInfoPtr__prefixes = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_prefixes");
			XmlTreeGen.NativeFieldInfoPtr__ds = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_ds");
			XmlTreeGen.NativeFieldInfoPtr__tables = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_tables");
			XmlTreeGen.NativeFieldInfoPtr__relations = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_relations");
			XmlTreeGen.NativeFieldInfoPtr__dc = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_dc");
			XmlTreeGen.NativeFieldInfoPtr__sRoot = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_sRoot");
			XmlTreeGen.NativeFieldInfoPtr__prefixCount = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_prefixCount");
			XmlTreeGen.NativeFieldInfoPtr__schFormat = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_schFormat");
			XmlTreeGen.NativeFieldInfoPtr__filePath = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_filePath");
			XmlTreeGen.NativeFieldInfoPtr__fileName = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_fileName");
			XmlTreeGen.NativeFieldInfoPtr__fileExt = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_fileExt");
			XmlTreeGen.NativeFieldInfoPtr__dsElement = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_dsElement");
			XmlTreeGen.NativeFieldInfoPtr__constraintSeparator = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_constraintSeparator");
			XmlTreeGen.NativeFieldInfoPtr__targetConverter = IL2CPP.GetIl2CppField(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, "_targetConverter");
			XmlTreeGen.NativeMethodInfoPtr__ctor_Internal_Void_SchemaFormat_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665349);
			XmlTreeGen.NativeMethodInfoPtr_AddExtendedProperties_Internal_Static_Void_PropertyCollection_XmlElement_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665350);
			XmlTreeGen.NativeMethodInfoPtr_AddExtendedProperties_Internal_Static_Void_PropertyCollection_XmlElement_Type_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665351);
			XmlTreeGen.NativeMethodInfoPtr_AddXdoProperties_Internal_Void_Object_XmlElement_XmlDocument_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665352);
			XmlTreeGen.NativeMethodInfoPtr_AddXdoProperty_Internal_Void_PropertyDescriptor_Object_XmlElement_XmlDocument_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665353);
			XmlTreeGen.NativeMethodInfoPtr_XmlDataTypeName_Internal_Static_String_Type_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665354);
			XmlTreeGen.NativeMethodInfoPtr_GenerateConstraintNames_Private_Void_DataTable_Boolean_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665355);
			XmlTreeGen.NativeMethodInfoPtr_GenerateConstraintNames_Private_Void_ArrayList_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665356);
			XmlTreeGen.NativeMethodInfoPtr_GenerateConstraintNames_Private_Void_DataSet_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665357);
			XmlTreeGen.NativeMethodInfoPtr__PropsNotEmpty_Private_Static_Boolean_PropertyCollection_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665358);
			XmlTreeGen.NativeMethodInfoPtr_HaveExtendedProperties_Private_Boolean_DataSet_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665359);
			XmlTreeGen.NativeMethodInfoPtr_WriteSchemaRoot_Internal_Void_XmlDocument_XmlElement_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665360);
			XmlTreeGen.NativeMethodInfoPtr_ValidateColumnMapping_Internal_Static_Void_Type_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665361);
			XmlTreeGen.NativeMethodInfoPtr_SetupAutoGenerated_Internal_Void_DataSet_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665362);
			XmlTreeGen.NativeMethodInfoPtr_SetupAutoGenerated_Internal_Void_ArrayList_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665363);
			XmlTreeGen.NativeMethodInfoPtr_SetupAutoGenerated_Internal_Void_DataTable_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665364);
			XmlTreeGen.NativeMethodInfoPtr_CreateTablesHierarchy_Private_Void_DataTable_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665365);
			XmlTreeGen.NativeMethodInfoPtr_CreateRelations_Private_Void_DataTable_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665366);
			XmlTreeGen.NativeMethodInfoPtr_CreateToplevelTables_Private_Il2CppReferenceArray_1_DataTable_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665367);
			XmlTreeGen.NativeMethodInfoPtr_SchemaTree_Internal_Void_XmlDocument_XmlWriter_DataSet_DataTable_Boolean_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665368);
			XmlTreeGen.NativeMethodInfoPtr_SchemaTree_Internal_XmlElement_XmlDocument_DataTable_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665369);
			XmlTreeGen.NativeMethodInfoPtr_FillDataSetElement_Internal_XmlElement_XmlDocument_DataSet_DataTable_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665370);
			XmlTreeGen.NativeMethodInfoPtr_SetPath_Internal_Void_XmlWriter_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665371);
			XmlTreeGen.NativeMethodInfoPtr_Save_Internal_Void_DataSet_XmlWriter_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665372);
			XmlTreeGen.NativeMethodInfoPtr_Save_Internal_Void_DataTable_XmlWriter_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665373);
			XmlTreeGen.NativeMethodInfoPtr_Save_Internal_Void_DataSet_DataTable_XmlWriter_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665374);
			XmlTreeGen.NativeMethodInfoPtr_Save_Internal_Void_DataSet_DataTable_XmlWriter_Boolean_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665375);
			XmlTreeGen.NativeMethodInfoPtr_Save_Internal_Void_DataSet_DataTable_XmlWriter_Boolean_Converter_2_Type_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665376);
			XmlTreeGen.NativeMethodInfoPtr_HandleRelation_Internal_XmlElement_DataRelation_XmlDocument_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665377);
			XmlTreeGen.NativeMethodInfoPtr_FindSimpleType_Private_Static_XmlElement_XmlElement_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665378);
			XmlTreeGen.NativeMethodInfoPtr_GetSchema_Internal_XmlElement_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665379);
			XmlTreeGen.NativeMethodInfoPtr_HandleColumnType_Internal_Void_DataColumn_XmlDocument_XmlElement_XmlElement_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665380);
			XmlTreeGen.NativeMethodInfoPtr_AddColumnProperties_Internal_Void_DataColumn_XmlElement_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665381);
			XmlTreeGen.NativeMethodInfoPtr_FindTargetNamespace_Private_String_DataTable_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665382);
			XmlTreeGen.NativeMethodInfoPtr_HandleColumn_Internal_XmlElement_DataColumn_XmlDocument_XmlElement_Boolean_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665383);
			XmlTreeGen.NativeMethodInfoPtr_TranslateAcceptRejectRule_Internal_Static_String_AcceptRejectRule_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665384);
			XmlTreeGen.NativeMethodInfoPtr_TranslateRule_Internal_Static_String_Rule_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665385);
			XmlTreeGen.NativeMethodInfoPtr_AppendChildWithoutRef_Internal_Void_XmlElement_String_XmlElement_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665386);
			XmlTreeGen.NativeMethodInfoPtr_FindTypeNode_Internal_XmlElement_XmlElement_String_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665387);
			XmlTreeGen.NativeMethodInfoPtr_HandleTable_Internal_XmlElement_DataTable_XmlDocument_XmlElement_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665388);
			XmlTreeGen.NativeMethodInfoPtr_HasMixedColumns_Private_Boolean_DataTable_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665389);
			XmlTreeGen.NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_DataColumn_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665390);
			XmlTreeGen.NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_DataRelation_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665391);
			XmlTreeGen.NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_UniqueConstraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665392);
			XmlTreeGen.NativeMethodInfoPtr_AutoGenerated_Private_Boolean_ForeignKeyConstraint_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665393);
			XmlTreeGen.NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_ForeignKeyConstraint_Boolean_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665394);
			XmlTreeGen.NativeMethodInfoPtr_IsAutoGenerated_Private_Boolean_Object_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665395);
			XmlTreeGen.NativeMethodInfoPtr_HandleTable_Internal_XmlElement_DataTable_XmlDocument_XmlElement_Boolean_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665396);
			XmlTreeGen.NativeMethodInfoPtr_SetMSDataAttribute_Private_Void_XmlElement_Type_0 = IL2CPP.GetIl2CppMethodByToken(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr, 100665397);
		}

		// Token: 0x06000C8D RID: 3213 RVA: 0x0003F9F0 File Offset: 0x0003DBF0
		[CallerCount(9)]
		[CachedScanResults(RefRangeStart = 912254, RefRangeEnd = 912263, XrefRangeStart = 912244, XrefRangeEnd = 912254, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe XmlTreeGen(SchemaFormat format)
			: this(IL2CPP.il2cpp_object_new(Il2CppClassPointerStore<XmlTreeGen>.NativeClassPtr))
		{
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = ref format;
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr__ctor_Internal_Void_SchemaFormat_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x06000C8E RID: 3214 RVA: 0x0003FA38 File Offset: 0x0003DC38
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 912263, XrefRangeEnd = 912264, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static void AddExtendedProperties(PropertyCollection props, XmlElement node)
		{
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(props);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(node);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AddExtendedProperties_Internal_Static_Void_PropertyCollection_XmlElement_0, 0, (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000C8F RID: 3215 RVA: 0x0003FA80 File Offset: 0x0003DC80
		[CallerCount(5)]
		[CachedScanResults(RefRangeStart = 912357, RefRangeEnd = 912362, XrefRangeStart = 912264, XrefRangeEnd = 912357, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static void AddExtendedProperties(PropertyCollection props, XmlElement node, Type type)
		{
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(props);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(node);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(type);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AddExtendedProperties_Internal_Static_Void_PropertyCollection_XmlElement_Type_0, 0, (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000C90 RID: 3216 RVA: 0x0003FADC File Offset: 0x0003DCDC
		[CallerCount(4)]
		[CachedScanResults(RefRangeStart = 912376, RefRangeEnd = 912380, XrefRangeStart = 912362, XrefRangeEnd = 912376, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void AddXdoProperties(Object instance, XmlElement root, XmlDocument xd)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(instance);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(root);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(xd);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AddXdoProperties_Internal_Void_Object_XmlElement_XmlDocument_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000C91 RID: 3217 RVA: 0x0003FB44 File Offset: 0x0003DD44
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 912483, RefRangeEnd = 912484, XrefRangeStart = 912380, XrefRangeEnd = 912483, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void AddXdoProperty(PropertyDescriptor pd, Object instance, XmlElement root, XmlDocument xd)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)4) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(pd);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(instance);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(root);
			ptr[checked(unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(xd);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AddXdoProperty_Internal_Void_PropertyDescriptor_Object_XmlElement_XmlDocument_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000C92 RID: 3218 RVA: 0x0003FBC0 File Offset: 0x0003DDC0
		[CallerCount(3)]
		[CachedScanResults(RefRangeStart = 912734, RefRangeEnd = 912737, XrefRangeStart = 912484, XrefRangeEnd = 912734, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static string XmlDataTypeName(Type type)
		{
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(type);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_XmlDataTypeName_Internal_Static_String_Type_0, 0, (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return IL2CPP.Il2CppStringToManaged(intPtr);
			}
		}

		// Token: 0x06000C93 RID: 3219 RVA: 0x0003FBFC File Offset: 0x0003DDFC
		[CallerCount(4)]
		[CachedScanResults(RefRangeStart = 912767, RefRangeEnd = 912771, XrefRangeStart = 912737, XrefRangeEnd = 912767, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void GenerateConstraintNames(DataTable table, bool fromTable)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(table);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref fromTable;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_GenerateConstraintNames_Private_Void_DataTable_Boolean_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000C94 RID: 3220 RVA: 0x0003FC4C File Offset: 0x0003DE4C
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 912771, XrefRangeEnd = 912775, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void GenerateConstraintNames(ArrayList tables)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(tables);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_GenerateConstraintNames_Private_Void_ArrayList_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x06000C95 RID: 3221 RVA: 0x0003FC90 File Offset: 0x0003DE90
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 912793, RefRangeEnd = 912794, XrefRangeStart = 912775, XrefRangeEnd = 912793, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void GenerateConstraintNames(DataSet ds)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(ds);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_GenerateConstraintNames_Private_Void_DataSet_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x06000C96 RID: 3222 RVA: 0x0003FCD4 File Offset: 0x0003DED4
		[CallerCount(0)]
		public unsafe static bool _PropsNotEmpty(PropertyCollection props)
		{
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(props);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr__PropsNotEmpty_Private_Static_Boolean_PropertyCollection_0, 0, (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x06000C97 RID: 3223 RVA: 0x0003FD18 File Offset: 0x0003DF18
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 912799, RefRangeEnd = 912800, XrefRangeStart = 912794, XrefRangeEnd = 912799, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe bool HaveExtendedProperties(DataSet ds)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(ds);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_HaveExtendedProperties_Private_Boolean_DataSet_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x06000C98 RID: 3224 RVA: 0x0003FD68 File Offset: 0x0003DF68
		[CallerCount(3)]
		[CachedScanResults(RefRangeStart = 912828, RefRangeEnd = 912831, XrefRangeStart = 912800, XrefRangeEnd = 912828, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void WriteSchemaRoot(XmlDocument xd, XmlElement rootSchema, string targetNamespace)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(xd);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(rootSchema);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.ManagedStringToIl2Cpp(targetNamespace);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_WriteSchemaRoot_Internal_Void_XmlDocument_XmlElement_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000C99 RID: 3225 RVA: 0x0003FDD0 File Offset: 0x0003DFD0
		[CallerCount(4)]
		[CachedScanResults(RefRangeStart = 912835, RefRangeEnd = 912839, XrefRangeStart = 912831, XrefRangeEnd = 912835, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static void ValidateColumnMapping(Type columnType)
		{
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(columnType);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_ValidateColumnMapping_Internal_Static_Void_Type_0, 0, (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x06000C9A RID: 3226 RVA: 0x0003FE08 File Offset: 0x0003E008
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 912857, RefRangeEnd = 912858, XrefRangeStart = 912839, XrefRangeEnd = 912857, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void SetupAutoGenerated(DataSet ds)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(ds);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_SetupAutoGenerated_Internal_Void_DataSet_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x06000C9B RID: 3227 RVA: 0x0003FE4C File Offset: 0x0003E04C
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 912858, XrefRangeEnd = 912862, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void SetupAutoGenerated(ArrayList dt)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(dt);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_SetupAutoGenerated_Internal_Void_ArrayList_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x06000C9C RID: 3228 RVA: 0x0003FE90 File Offset: 0x0003E090
		[CallerCount(3)]
		[CachedScanResults(RefRangeStart = 912916, RefRangeEnd = 912919, XrefRangeStart = 912862, XrefRangeEnd = 912916, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void SetupAutoGenerated(DataTable dt)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(dt);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_SetupAutoGenerated_Internal_Void_DataTable_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x06000C9D RID: 3229 RVA: 0x0003FED4 File Offset: 0x0003E0D4
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 912938, RefRangeEnd = 912940, XrefRangeStart = 912919, XrefRangeEnd = 912938, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void CreateTablesHierarchy(DataTable dt)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(dt);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_CreateTablesHierarchy_Private_Void_DataTable_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x06000C9E RID: 3230 RVA: 0x0003FF18 File Offset: 0x0003E118
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 912959, RefRangeEnd = 912961, XrefRangeStart = 912940, XrefRangeEnd = 912959, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void CreateRelations(DataTable dt)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(dt);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_CreateRelations_Private_Void_DataTable_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x06000C9F RID: 3231 RVA: 0x0003FF5C File Offset: 0x0003E15C
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 912977, RefRangeEnd = 912978, XrefRangeStart = 912961, XrefRangeEnd = 912977, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe Il2CppReferenceArray<DataTable> CreateToplevelTables()
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr = null;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_CreateToplevelTables_Private_Il2CppReferenceArray_1_DataTable_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<Il2CppReferenceArray<DataTable>>(intPtr3) : null;
		}

		// Token: 0x06000CA0 RID: 3232 RVA: 0x0003FF9C File Offset: 0x0003E19C
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 913315, RefRangeEnd = 913317, XrefRangeStart = 912978, XrefRangeEnd = 913315, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void SchemaTree(XmlDocument xd, XmlWriter xmlWriter, DataSet ds, DataTable dt, bool writeHierarchy)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)5) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(xd);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(xmlWriter);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(ds);
			ptr[checked(unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dt);
			ptr[checked(unchecked((UIntPtr)4) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref writeHierarchy;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_SchemaTree_Internal_Void_XmlDocument_XmlWriter_DataSet_DataTable_Boolean_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000CA1 RID: 3233 RVA: 0x00040024 File Offset: 0x0003E224
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 913373, RefRangeEnd = 913374, XrefRangeStart = 913317, XrefRangeEnd = 913373, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe XmlElement SchemaTree(XmlDocument xd, DataTable dt)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(xd);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dt);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_SchemaTree_Internal_XmlElement_XmlDocument_DataTable_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr3) : null;
		}

		// Token: 0x06000CA2 RID: 3234 RVA: 0x00040088 File Offset: 0x0003E288
		[CallerCount(3)]
		[CachedScanResults(RefRangeStart = 913462, RefRangeEnd = 913465, XrefRangeStart = 913374, XrefRangeEnd = 913462, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe XmlElement FillDataSetElement(XmlDocument xd, DataSet ds, DataTable dt)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(xd);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(ds);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dt);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_FillDataSetElement_Internal_XmlElement_XmlDocument_DataSet_DataTable_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr3) : null;
		}

		// Token: 0x06000CA3 RID: 3235 RVA: 0x000400FC File Offset: 0x0003E2FC
		[CallerCount(3)]
		[CachedScanResults(RefRangeStart = 913498, RefRangeEnd = 913501, XrefRangeStart = 913465, XrefRangeEnd = 913498, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void SetPath(XmlWriter xw)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(xw);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_SetPath_Internal_Void_XmlWriter_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			}
		}

		// Token: 0x06000CA4 RID: 3236 RVA: 0x00040140 File Offset: 0x0003E340
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 913502, RefRangeEnd = 913504, XrefRangeStart = 913501, XrefRangeEnd = 913502, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void Save(DataSet ds, XmlWriter xw)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(ds);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(xw);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_Save_Internal_Void_DataSet_XmlWriter_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000CA5 RID: 3237 RVA: 0x00040194 File Offset: 0x0003E394
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 913511, RefRangeEnd = 913513, XrefRangeStart = 913504, XrefRangeEnd = 913511, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void Save(DataTable dt, XmlWriter xw)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(dt);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(xw);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_Save_Internal_Void_DataTable_XmlWriter_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000CA6 RID: 3238 RVA: 0x000401E8 File Offset: 0x0003E3E8
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 913513, XrefRangeEnd = 913514, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void Save(DataSet ds, DataTable dt, XmlWriter xw)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(ds);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dt);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(xw);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_Save_Internal_Void_DataSet_DataTable_XmlWriter_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000CA7 RID: 3239 RVA: 0x00040250 File Offset: 0x0003E450
		[CallerCount(4)]
		[CachedScanResults(RefRangeStart = 913530, RefRangeEnd = 913534, XrefRangeStart = 913514, XrefRangeEnd = 913530, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)4) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(ds);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dt);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(xw);
			ptr[checked(unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref writeHierarchy;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_Save_Internal_Void_DataSet_DataTable_XmlWriter_Boolean_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000CA8 RID: 3240 RVA: 0x000402C4 File Offset: 0x0003E4C4
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 913551, RefRangeEnd = 913552, XrefRangeStart = 913534, XrefRangeEnd = 913551, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy, Converter<Type, string> multipleTargetConverter)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)5) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(ds);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dt);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(xw);
			ptr[checked(unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref writeHierarchy;
			ptr[checked(unchecked((UIntPtr)4) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(multipleTargetConverter);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_Save_Internal_Void_DataSet_DataTable_XmlWriter_Boolean_Converter_2_Type_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000CA9 RID: 3241 RVA: 0x0004034C File Offset: 0x0003E54C
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 913624, RefRangeEnd = 913625, XrefRangeStart = 913552, XrefRangeEnd = 913624, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe XmlElement HandleRelation(DataRelation rel, XmlDocument dc)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(rel);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dc);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_HandleRelation_Internal_XmlElement_DataRelation_XmlDocument_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr3) : null;
		}

		// Token: 0x06000CAA RID: 3242 RVA: 0x000403B0 File Offset: 0x0003E5B0
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 913625, XrefRangeEnd = 913630, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static XmlElement FindSimpleType(XmlElement schema, string name)
		{
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(schema);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.ManagedStringToIl2Cpp(name);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_FindSimpleType_Private_Static_XmlElement_XmlElement_String_0, 0, (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr3) : null;
		}

		// Token: 0x06000CAB RID: 3243 RVA: 0x00040408 File Offset: 0x0003E608
		[CallerCount(3)]
		[CachedScanResults(RefRangeStart = 913657, RefRangeEnd = 913660, XrefRangeStart = 913630, XrefRangeEnd = 913657, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe XmlElement GetSchema(string NamespaceURI)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.ManagedStringToIl2Cpp(NamespaceURI);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_GetSchema_Internal_XmlElement_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				IntPtr intPtr3 = intPtr;
				return (intPtr3 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr3) : null;
			}
		}

		// Token: 0x06000CAC RID: 3244 RVA: 0x00040458 File Offset: 0x0003E658
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 913678, RefRangeEnd = 913679, XrefRangeStart = 913660, XrefRangeEnd = 913678, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void HandleColumnType(DataColumn col, XmlDocument dc, XmlElement root, XmlElement schema)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)4) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(col);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dc);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(root);
			ptr[checked(unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(schema);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_HandleColumnType_Internal_Void_DataColumn_XmlDocument_XmlElement_XmlElement_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000CAD RID: 3245 RVA: 0x000404D4 File Offset: 0x0003E6D4
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 913771, RefRangeEnd = 913772, XrefRangeStart = 913679, XrefRangeEnd = 913771, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void AddColumnProperties(DataColumn col, XmlElement root)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(col);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(root);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AddColumnProperties_Internal_Void_DataColumn_XmlElement_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000CAE RID: 3246 RVA: 0x00040528 File Offset: 0x0003E728
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 913778, RefRangeEnd = 913779, XrefRangeStart = 913772, XrefRangeEnd = 913778, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe string FindTargetNamespace(DataTable table)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(table);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_FindTargetNamespace_Private_String_DataTable_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return IL2CPP.Il2CppStringToManaged(intPtr);
			}
		}

		// Token: 0x06000CAF RID: 3247 RVA: 0x00040570 File Offset: 0x0003E770
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 913779, XrefRangeEnd = 913931, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe XmlElement HandleColumn(DataColumn col, XmlDocument dc, XmlElement schema, bool fWriteOrdinal)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)4) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(col);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dc);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(schema);
			ptr[checked(unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref fWriteOrdinal;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_HandleColumn_Internal_XmlElement_DataColumn_XmlDocument_XmlElement_Boolean_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr3) : null;
		}

		// Token: 0x06000CB0 RID: 3248 RVA: 0x000405F4 File Offset: 0x0003E7F4
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 913931, XrefRangeEnd = 913934, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static string TranslateAcceptRejectRule(AcceptRejectRule rule)
		{
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = ref rule;
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_TranslateAcceptRejectRule_Internal_Static_String_AcceptRejectRule_0, 0, (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return IL2CPP.Il2CppStringToManaged(intPtr);
			}
		}

		// Token: 0x06000CB1 RID: 3249 RVA: 0x0004062C File Offset: 0x0003E82C
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 913934, XrefRangeEnd = 913938, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static string TranslateRule(Rule rule)
		{
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = ref rule;
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_TranslateRule_Internal_Static_String_Rule_0, 0, (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return IL2CPP.Il2CppStringToManaged(intPtr);
			}
		}

		// Token: 0x06000CB2 RID: 3250 RVA: 0x00040664 File Offset: 0x0003E864
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 913942, RefRangeEnd = 913943, XrefRangeStart = 913938, XrefRangeEnd = 913942, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void AppendChildWithoutRef(XmlElement node, string Namespace, XmlElement el, string refString)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)4) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(node);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.ManagedStringToIl2Cpp(Namespace);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(el);
			ptr[checked(unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.ManagedStringToIl2Cpp(refString);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AppendChildWithoutRef_Internal_Void_XmlElement_String_XmlElement_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000CB3 RID: 3251 RVA: 0x000406E0 File Offset: 0x0003E8E0
		[CallerCount(2)]
		[CachedScanResults(RefRangeStart = 913965, RefRangeEnd = 913967, XrefRangeStart = 913943, XrefRangeEnd = 913965, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe XmlElement FindTypeNode(XmlElement node, string strType)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(node);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.ManagedStringToIl2Cpp(strType);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_FindTypeNode_Internal_XmlElement_XmlElement_String_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr3) : null;
		}

		// Token: 0x06000CB4 RID: 3252 RVA: 0x00040744 File Offset: 0x0003E944
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 913967, XrefRangeEnd = 913968, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(table);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dc);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(schema);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_HandleTable_Internal_XmlElement_DataTable_XmlDocument_XmlElement_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr3) : null;
		}

		// Token: 0x06000CB5 RID: 3253 RVA: 0x000407B8 File Offset: 0x0003E9B8
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 913968, XrefRangeEnd = 913978, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe bool HasMixedColumns(DataTable table)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(table);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_HasMixedColumns_Private_Boolean_DataTable_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x06000CB6 RID: 3254 RVA: 0x00040808 File Offset: 0x0003EA08
		[CallerCount(4)]
		[CachedScanResults(RefRangeStart = 914021, RefRangeEnd = 914025, XrefRangeStart = 913978, XrefRangeEnd = 914021, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static bool AutoGenerated(DataColumn col)
		{
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(col);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_DataColumn_0, 0, (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x06000CB7 RID: 3255 RVA: 0x0004084C File Offset: 0x0003EA4C
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 914030, RefRangeEnd = 914031, XrefRangeStart = 914025, XrefRangeEnd = 914030, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static bool AutoGenerated(DataRelation rel)
		{
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(rel);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_DataRelation_0, 0, (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x06000CB8 RID: 3256 RVA: 0x00040890 File Offset: 0x0003EA90
		[CallerCount(4)]
		[CachedScanResults(RefRangeStart = 914036, RefRangeEnd = 914040, XrefRangeStart = 914031, XrefRangeEnd = 914036, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static bool AutoGenerated(UniqueConstraint unique)
		{
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(unique);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_UniqueConstraint_0, 0, (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x06000CB9 RID: 3257 RVA: 0x000408D4 File Offset: 0x0003EAD4
		[CallerCount(0)]
		[CachedScanResults(RefRangeStart = 0, RefRangeEnd = 0, XrefRangeStart = 914040, XrefRangeEnd = 914041, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe bool AutoGenerated(ForeignKeyConstraint fk)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(fk);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AutoGenerated_Private_Boolean_ForeignKeyConstraint_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x06000CBA RID: 3258 RVA: 0x00040924 File Offset: 0x0003EB24
		[CallerCount(5)]
		[CachedScanResults(RefRangeStart = 914052, RefRangeEnd = 914057, XrefRangeStart = 914041, XrefRangeEnd = 914052, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe static bool AutoGenerated(ForeignKeyConstraint fk, bool checkRelation)
		{
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(fk);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref checkRelation;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_ForeignKeyConstraint_Boolean_0, 0, (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			return *IL2CPP.il2cpp_object_unbox(intPtr);
		}

		// Token: 0x06000CBB RID: 3259 RVA: 0x00040974 File Offset: 0x0003EB74
		[CallerCount(0)]
		public unsafe bool IsAutoGenerated(Object o)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			checked
			{
				IntPtr* ptr = stackalloc IntPtr[unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(o);
				IntPtr intPtr2;
				IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_IsAutoGenerated_Private_Boolean_Object_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
				Il2CppException.RaiseExceptionIfNecessary(intPtr2);
				return *IL2CPP.il2cpp_object_unbox(intPtr);
			}
		}

		// Token: 0x06000CBC RID: 3260 RVA: 0x000409C4 File Offset: 0x0003EBC4
		[CallerCount(3)]
		[CachedScanResults(RefRangeStart = 914163, RefRangeEnd = 914166, XrefRangeStart = 914057, XrefRangeEnd = 914163, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema, bool genNested)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)4) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(table);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(dc);
			ptr[checked(unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(schema);
			ptr[checked(unchecked((UIntPtr)3) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = ref genNested;
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_HandleTable_Internal_XmlElement_DataTable_XmlDocument_XmlElement_Boolean_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
			IntPtr intPtr3 = intPtr;
			return (intPtr3 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr3) : null;
		}

		// Token: 0x06000CBD RID: 3261 RVA: 0x00040A48 File Offset: 0x0003EC48
		[CallerCount(1)]
		[CachedScanResults(RefRangeStart = 914185, RefRangeEnd = 914186, XrefRangeStart = 914166, XrefRangeEnd = 914185, MetadataInitTokenRva = 0L, MetadataInitFlagRva = 0L)]
		public unsafe void SetMSDataAttribute(XmlElement root, Type type)
		{
			IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
			IntPtr* ptr;
			checked
			{
				ptr = stackalloc IntPtr[unchecked((UIntPtr)2) * (UIntPtr)sizeof(IntPtr)];
				*ptr = IL2CPP.Il2CppObjectBaseToPtr(root);
			}
			ptr[checked(unchecked((UIntPtr)1) * (UIntPtr)sizeof(IntPtr)) / (UIntPtr)sizeof(IntPtr)] = IL2CPP.Il2CppObjectBaseToPtr(type);
			IntPtr intPtr2;
			IntPtr intPtr = IL2CPP.il2cpp_runtime_invoke(XmlTreeGen.NativeMethodInfoPtr_SetMSDataAttribute_Private_Void_XmlElement_Type_0, IL2CPP.Il2CppObjectBaseToPtrNotNull(this), (void**)ptr, ref intPtr2);
			Il2CppException.RaiseExceptionIfNecessary(intPtr2);
		}

		// Token: 0x06000CBE RID: 3262 RVA: 0x00005F3E File Offset: 0x0000413E
		public XmlTreeGen(IntPtr pointer)
			: base(pointer)
		{
		}

		// Token: 0x1700031B RID: 795
		// (get) Token: 0x06000CBF RID: 3263 RVA: 0x00040A9C File Offset: 0x0003EC9C
		// (set) Token: 0x06000CC0 RID: 3264 RVA: 0x00005F47 File Offset: 0x00004147
		public unsafe ArrayList _constraintNames
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__constraintNames);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<ArrayList>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__constraintNames), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x1700031C RID: 796
		// (get) Token: 0x06000CC1 RID: 3265 RVA: 0x00040ACC File Offset: 0x0003ECCC
		// (set) Token: 0x06000CC2 RID: 3266 RVA: 0x00005F66 File Offset: 0x00004166
		public unsafe Hashtable _namespaces
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__namespaces);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<Hashtable>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__namespaces), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x1700031D RID: 797
		// (get) Token: 0x06000CC3 RID: 3267 RVA: 0x00040AFC File Offset: 0x0003ECFC
		// (set) Token: 0x06000CC4 RID: 3268 RVA: 0x00005F85 File Offset: 0x00004185
		public unsafe Hashtable _autogenerated
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__autogenerated);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<Hashtable>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__autogenerated), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x1700031E RID: 798
		// (get) Token: 0x06000CC5 RID: 3269 RVA: 0x00040B2C File Offset: 0x0003ED2C
		// (set) Token: 0x06000CC6 RID: 3270 RVA: 0x00005FA4 File Offset: 0x000041A4
		public unsafe Hashtable _prefixes
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__prefixes);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<Hashtable>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__prefixes), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x1700031F RID: 799
		// (get) Token: 0x06000CC7 RID: 3271 RVA: 0x00040B5C File Offset: 0x0003ED5C
		// (set) Token: 0x06000CC8 RID: 3272 RVA: 0x00005FC3 File Offset: 0x000041C3
		public unsafe DataSet _ds
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__ds);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<DataSet>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__ds), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x17000320 RID: 800
		// (get) Token: 0x06000CC9 RID: 3273 RVA: 0x00040B8C File Offset: 0x0003ED8C
		// (set) Token: 0x06000CCA RID: 3274 RVA: 0x00005FE2 File Offset: 0x000041E2
		public unsafe ArrayList _tables
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__tables);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<ArrayList>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__tables), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x17000321 RID: 801
		// (get) Token: 0x06000CCB RID: 3275 RVA: 0x00040BBC File Offset: 0x0003EDBC
		// (set) Token: 0x06000CCC RID: 3276 RVA: 0x00006001 File Offset: 0x00004201
		public unsafe ArrayList _relations
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__relations);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<ArrayList>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__relations), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x17000322 RID: 802
		// (get) Token: 0x06000CCD RID: 3277 RVA: 0x00040BEC File Offset: 0x0003EDEC
		// (set) Token: 0x06000CCE RID: 3278 RVA: 0x00006020 File Offset: 0x00004220
		public unsafe XmlDocument _dc
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__dc);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<XmlDocument>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__dc), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x17000323 RID: 803
		// (get) Token: 0x06000CCF RID: 3279 RVA: 0x00040C1C File Offset: 0x0003EE1C
		// (set) Token: 0x06000CD0 RID: 3280 RVA: 0x0000603F File Offset: 0x0000423F
		public unsafe XmlElement _sRoot
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__sRoot);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__sRoot), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x17000324 RID: 804
		// (get) Token: 0x06000CD1 RID: 3281 RVA: 0x00040C4C File Offset: 0x0003EE4C
		// (set) Token: 0x06000CD2 RID: 3282 RVA: 0x0000605E File Offset: 0x0000425E
		public unsafe int _prefixCount
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__prefixCount);
				return *intPtr;
			}
			set
			{
				*(IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__prefixCount)) = value;
			}
		}

		// Token: 0x17000325 RID: 805
		// (get) Token: 0x06000CD3 RID: 3283 RVA: 0x00040C74 File Offset: 0x0003EE74
		// (set) Token: 0x06000CD4 RID: 3284 RVA: 0x00006079 File Offset: 0x00004279
		public unsafe SchemaFormat _schFormat
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__schFormat);
				return *intPtr;
			}
			set
			{
				*(IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__schFormat)) = value;
			}
		}

		// Token: 0x17000326 RID: 806
		// (get) Token: 0x06000CD5 RID: 3285 RVA: 0x00040C9C File Offset: 0x0003EE9C
		// (set) Token: 0x06000CD6 RID: 3286 RVA: 0x00006094 File Offset: 0x00004294
		public unsafe string _filePath
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__filePath);
				return IL2CPP.Il2CppStringToManaged(*intPtr);
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__filePath), IL2CPP.ManagedStringToIl2Cpp(value));
			}
		}

		// Token: 0x17000327 RID: 807
		// (get) Token: 0x06000CD7 RID: 3287 RVA: 0x00040CC4 File Offset: 0x0003EEC4
		// (set) Token: 0x06000CD8 RID: 3288 RVA: 0x000060B3 File Offset: 0x000042B3
		public unsafe string _fileName
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__fileName);
				return IL2CPP.Il2CppStringToManaged(*intPtr);
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__fileName), IL2CPP.ManagedStringToIl2Cpp(value));
			}
		}

		// Token: 0x17000328 RID: 808
		// (get) Token: 0x06000CD9 RID: 3289 RVA: 0x00040CEC File Offset: 0x0003EEEC
		// (set) Token: 0x06000CDA RID: 3290 RVA: 0x000060D2 File Offset: 0x000042D2
		public unsafe string _fileExt
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__fileExt);
				return IL2CPP.Il2CppStringToManaged(*intPtr);
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__fileExt), IL2CPP.ManagedStringToIl2Cpp(value));
			}
		}

		// Token: 0x17000329 RID: 809
		// (get) Token: 0x06000CDB RID: 3291 RVA: 0x00040D14 File Offset: 0x0003EF14
		// (set) Token: 0x06000CDC RID: 3292 RVA: 0x000060F1 File Offset: 0x000042F1
		public unsafe XmlElement _dsElement
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__dsElement);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__dsElement), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x1700032A RID: 810
		// (get) Token: 0x06000CDD RID: 3293 RVA: 0x00040D44 File Offset: 0x0003EF44
		// (set) Token: 0x06000CDE RID: 3294 RVA: 0x00006110 File Offset: 0x00004310
		public unsafe XmlElement _constraintSeparator
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__constraintSeparator);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<XmlElement>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__constraintSeparator), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x1700032B RID: 811
		// (get) Token: 0x06000CDF RID: 3295 RVA: 0x00040D74 File Offset: 0x0003EF74
		// (set) Token: 0x06000CE0 RID: 3296 RVA: 0x0000612F File Offset: 0x0000432F
		public unsafe Converter<Type, string> _targetConverter
		{
			get
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this) + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__targetConverter);
				IntPtr intPtr2 = *intPtr;
				return (intPtr2 != 0) ? Il2CppObjectPool.Get<Converter<Type, string>>(intPtr2) : null;
			}
			set
			{
				IntPtr intPtr = IL2CPP.Il2CppObjectBaseToPtrNotNull(this);
				IL2CPP.il2cpp_gc_wbarrier_set_field(intPtr, intPtr + (IntPtr)IL2CPP.il2cpp_field_get_offset(XmlTreeGen.NativeFieldInfoPtr__targetConverter), IL2CPP.Il2CppObjectBaseToPtr(value));
			}
		}

		// Token: 0x04000A6C RID: 2668
		private static readonly IntPtr NativeFieldInfoPtr__constraintNames;

		// Token: 0x04000A6D RID: 2669
		private static readonly IntPtr NativeFieldInfoPtr__namespaces;

		// Token: 0x04000A6E RID: 2670
		private static readonly IntPtr NativeFieldInfoPtr__autogenerated;

		// Token: 0x04000A6F RID: 2671
		private static readonly IntPtr NativeFieldInfoPtr__prefixes;

		// Token: 0x04000A70 RID: 2672
		private static readonly IntPtr NativeFieldInfoPtr__ds;

		// Token: 0x04000A71 RID: 2673
		private static readonly IntPtr NativeFieldInfoPtr__tables;

		// Token: 0x04000A72 RID: 2674
		private static readonly IntPtr NativeFieldInfoPtr__relations;

		// Token: 0x04000A73 RID: 2675
		private static readonly IntPtr NativeFieldInfoPtr__dc;

		// Token: 0x04000A74 RID: 2676
		private static readonly IntPtr NativeFieldInfoPtr__sRoot;

		// Token: 0x04000A75 RID: 2677
		private static readonly IntPtr NativeFieldInfoPtr__prefixCount;

		// Token: 0x04000A76 RID: 2678
		private static readonly IntPtr NativeFieldInfoPtr__schFormat;

		// Token: 0x04000A77 RID: 2679
		private static readonly IntPtr NativeFieldInfoPtr__filePath;

		// Token: 0x04000A78 RID: 2680
		private static readonly IntPtr NativeFieldInfoPtr__fileName;

		// Token: 0x04000A79 RID: 2681
		private static readonly IntPtr NativeFieldInfoPtr__fileExt;

		// Token: 0x04000A7A RID: 2682
		private static readonly IntPtr NativeFieldInfoPtr__dsElement;

		// Token: 0x04000A7B RID: 2683
		private static readonly IntPtr NativeFieldInfoPtr__constraintSeparator;

		// Token: 0x04000A7C RID: 2684
		private static readonly IntPtr NativeFieldInfoPtr__targetConverter;

		// Token: 0x04000A7D RID: 2685
		private static readonly IntPtr NativeMethodInfoPtr__ctor_Internal_Void_SchemaFormat_0;

		// Token: 0x04000A7E RID: 2686
		private static readonly IntPtr NativeMethodInfoPtr_AddExtendedProperties_Internal_Static_Void_PropertyCollection_XmlElement_0;

		// Token: 0x04000A7F RID: 2687
		private static readonly IntPtr NativeMethodInfoPtr_AddExtendedProperties_Internal_Static_Void_PropertyCollection_XmlElement_Type_0;

		// Token: 0x04000A80 RID: 2688
		private static readonly IntPtr NativeMethodInfoPtr_AddXdoProperties_Internal_Void_Object_XmlElement_XmlDocument_0;

		// Token: 0x04000A81 RID: 2689
		private static readonly IntPtr NativeMethodInfoPtr_AddXdoProperty_Internal_Void_PropertyDescriptor_Object_XmlElement_XmlDocument_0;

		// Token: 0x04000A82 RID: 2690
		private static readonly IntPtr NativeMethodInfoPtr_XmlDataTypeName_Internal_Static_String_Type_0;

		// Token: 0x04000A83 RID: 2691
		private static readonly IntPtr NativeMethodInfoPtr_GenerateConstraintNames_Private_Void_DataTable_Boolean_0;

		// Token: 0x04000A84 RID: 2692
		private static readonly IntPtr NativeMethodInfoPtr_GenerateConstraintNames_Private_Void_ArrayList_0;

		// Token: 0x04000A85 RID: 2693
		private static readonly IntPtr NativeMethodInfoPtr_GenerateConstraintNames_Private_Void_DataSet_0;

		// Token: 0x04000A86 RID: 2694
		private static readonly IntPtr NativeMethodInfoPtr__PropsNotEmpty_Private_Static_Boolean_PropertyCollection_0;

		// Token: 0x04000A87 RID: 2695
		private static readonly IntPtr NativeMethodInfoPtr_HaveExtendedProperties_Private_Boolean_DataSet_0;

		// Token: 0x04000A88 RID: 2696
		private static readonly IntPtr NativeMethodInfoPtr_WriteSchemaRoot_Internal_Void_XmlDocument_XmlElement_String_0;

		// Token: 0x04000A89 RID: 2697
		private static readonly IntPtr NativeMethodInfoPtr_ValidateColumnMapping_Internal_Static_Void_Type_0;

		// Token: 0x04000A8A RID: 2698
		private static readonly IntPtr NativeMethodInfoPtr_SetupAutoGenerated_Internal_Void_DataSet_0;

		// Token: 0x04000A8B RID: 2699
		private static readonly IntPtr NativeMethodInfoPtr_SetupAutoGenerated_Internal_Void_ArrayList_0;

		// Token: 0x04000A8C RID: 2700
		private static readonly IntPtr NativeMethodInfoPtr_SetupAutoGenerated_Internal_Void_DataTable_0;

		// Token: 0x04000A8D RID: 2701
		private static readonly IntPtr NativeMethodInfoPtr_CreateTablesHierarchy_Private_Void_DataTable_0;

		// Token: 0x04000A8E RID: 2702
		private static readonly IntPtr NativeMethodInfoPtr_CreateRelations_Private_Void_DataTable_0;

		// Token: 0x04000A8F RID: 2703
		private static readonly IntPtr NativeMethodInfoPtr_CreateToplevelTables_Private_Il2CppReferenceArray_1_DataTable_0;

		// Token: 0x04000A90 RID: 2704
		private static readonly IntPtr NativeMethodInfoPtr_SchemaTree_Internal_Void_XmlDocument_XmlWriter_DataSet_DataTable_Boolean_0;

		// Token: 0x04000A91 RID: 2705
		private static readonly IntPtr NativeMethodInfoPtr_SchemaTree_Internal_XmlElement_XmlDocument_DataTable_0;

		// Token: 0x04000A92 RID: 2706
		private static readonly IntPtr NativeMethodInfoPtr_FillDataSetElement_Internal_XmlElement_XmlDocument_DataSet_DataTable_0;

		// Token: 0x04000A93 RID: 2707
		private static readonly IntPtr NativeMethodInfoPtr_SetPath_Internal_Void_XmlWriter_0;

		// Token: 0x04000A94 RID: 2708
		private static readonly IntPtr NativeMethodInfoPtr_Save_Internal_Void_DataSet_XmlWriter_0;

		// Token: 0x04000A95 RID: 2709
		private static readonly IntPtr NativeMethodInfoPtr_Save_Internal_Void_DataTable_XmlWriter_0;

		// Token: 0x04000A96 RID: 2710
		private static readonly IntPtr NativeMethodInfoPtr_Save_Internal_Void_DataSet_DataTable_XmlWriter_0;

		// Token: 0x04000A97 RID: 2711
		private static readonly IntPtr NativeMethodInfoPtr_Save_Internal_Void_DataSet_DataTable_XmlWriter_Boolean_0;

		// Token: 0x04000A98 RID: 2712
		private static readonly IntPtr NativeMethodInfoPtr_Save_Internal_Void_DataSet_DataTable_XmlWriter_Boolean_Converter_2_Type_String_0;

		// Token: 0x04000A99 RID: 2713
		private static readonly IntPtr NativeMethodInfoPtr_HandleRelation_Internal_XmlElement_DataRelation_XmlDocument_0;

		// Token: 0x04000A9A RID: 2714
		private static readonly IntPtr NativeMethodInfoPtr_FindSimpleType_Private_Static_XmlElement_XmlElement_String_0;

		// Token: 0x04000A9B RID: 2715
		private static readonly IntPtr NativeMethodInfoPtr_GetSchema_Internal_XmlElement_String_0;

		// Token: 0x04000A9C RID: 2716
		private static readonly IntPtr NativeMethodInfoPtr_HandleColumnType_Internal_Void_DataColumn_XmlDocument_XmlElement_XmlElement_0;

		// Token: 0x04000A9D RID: 2717
		private static readonly IntPtr NativeMethodInfoPtr_AddColumnProperties_Internal_Void_DataColumn_XmlElement_0;

		// Token: 0x04000A9E RID: 2718
		private static readonly IntPtr NativeMethodInfoPtr_FindTargetNamespace_Private_String_DataTable_0;

		// Token: 0x04000A9F RID: 2719
		private static readonly IntPtr NativeMethodInfoPtr_HandleColumn_Internal_XmlElement_DataColumn_XmlDocument_XmlElement_Boolean_0;

		// Token: 0x04000AA0 RID: 2720
		private static readonly IntPtr NativeMethodInfoPtr_TranslateAcceptRejectRule_Internal_Static_String_AcceptRejectRule_0;

		// Token: 0x04000AA1 RID: 2721
		private static readonly IntPtr NativeMethodInfoPtr_TranslateRule_Internal_Static_String_Rule_0;

		// Token: 0x04000AA2 RID: 2722
		private static readonly IntPtr NativeMethodInfoPtr_AppendChildWithoutRef_Internal_Void_XmlElement_String_XmlElement_String_0;

		// Token: 0x04000AA3 RID: 2723
		private static readonly IntPtr NativeMethodInfoPtr_FindTypeNode_Internal_XmlElement_XmlElement_String_0;

		// Token: 0x04000AA4 RID: 2724
		private static readonly IntPtr NativeMethodInfoPtr_HandleTable_Internal_XmlElement_DataTable_XmlDocument_XmlElement_0;

		// Token: 0x04000AA5 RID: 2725
		private static readonly IntPtr NativeMethodInfoPtr_HasMixedColumns_Private_Boolean_DataTable_0;

		// Token: 0x04000AA6 RID: 2726
		private static readonly IntPtr NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_DataColumn_0;

		// Token: 0x04000AA7 RID: 2727
		private static readonly IntPtr NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_DataRelation_0;

		// Token: 0x04000AA8 RID: 2728
		private static readonly IntPtr NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_UniqueConstraint_0;

		// Token: 0x04000AA9 RID: 2729
		private static readonly IntPtr NativeMethodInfoPtr_AutoGenerated_Private_Boolean_ForeignKeyConstraint_0;

		// Token: 0x04000AAA RID: 2730
		private static readonly IntPtr NativeMethodInfoPtr_AutoGenerated_Internal_Static_Boolean_ForeignKeyConstraint_Boolean_0;

		// Token: 0x04000AAB RID: 2731
		private static readonly IntPtr NativeMethodInfoPtr_IsAutoGenerated_Private_Boolean_Object_0;

		// Token: 0x04000AAC RID: 2732
		private static readonly IntPtr NativeMethodInfoPtr_HandleTable_Internal_XmlElement_DataTable_XmlDocument_XmlElement_Boolean_0;

		// Token: 0x04000AAD RID: 2733
		private static readonly IntPtr NativeMethodInfoPtr_SetMSDataAttribute_Private_Void_XmlElement_Type_0;
	}
}
